//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShaminPart4
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeluxeHamburger
    {
        public int id_deluxe { get; set; }
        public string bread { get; set; }
        public string meat { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<int> id_sale { get; set; }
    
        public virtual Sale Sale { get; set; }
    }
}
